### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/EMMA_la_dash#1]
Overview page is a default landing page for Learning Analytics dashboards which displays general statistics for the current (selected) course.

Graph generates bars for number of total interactions per lessons and curved line for average time spent by users per lessons and most popular resources within the course.

Data is viewable on scalable graph which can extend if needed.

Average time spent is presented in minutes.

Table of the most popular resources displays 10 most popular resources with link to resource and number of total views. Depending of the language chosen by user, table may display data for same resource in several rows (for example, English version may have more views than Estonian version of the resource).

**NB! order of tabs will be Overview-Lessons-Participants-Activity stream-SNA**

![screen shot 2015-08-21 at 13 49 00](https://cloud.githubusercontent.com/assets/380007/9406701/9a4883dc-480b-11e5-848b-77d5624ea0fc.png)

**Comment by pjotrsavitski** [comment]
Working, although might need a few tweaks here and there.

**Comment by pjotrsavitski** [comment]
The number of most popular resources to sow should be 10 or 25? Currently it is 25 in code.

**Comment by pjotrsavitski** [comment]
I consider this one almost done, unless there are any issues with queries.

**Comment by pjotrsavitski** [comment]
Done, create new smaller issues if changes are required.
