### ISSUE TITLE
Activity stream

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/EMMA_la_dash#2]
Activity stream page displays 25 most recent activities regarding to current (selected) course.

User sees timestamp (HH:MM) and activity statement as user-did that-object. Using a link beneath the statement, user access current object in the system.

If there is less than 25 statements for current date, older statements from previous days may be presented to user.

![screen shot 2015-08-07 at 14 03 01](https://cloud.githubusercontent.com/assets/380007/9134568/0d144af8-3d0e-11e5-84e9-0aa5c1f9c974.png)

**Comment by pjotrsavitski** [comment]
So the logic is to group these activities to under corresponding dates and then show these grouped?
Something like: 20/06/2014 >> 14:40 >> 13:20 >> 12:50 16/06/2014 >> 19:14 >> 12:50 That probably will not be like that as there will probably be a lot of activities about viewing something.

**Comment by pjotrsavitski** [comment]
Stream data is in, just needs to be modified to have the same look and feel.

**Comment by pjotrsavitski** [comment]
Done, create new smaller issues if changes are required.
