### ISSUE TITLE
Social network analysis

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/EMMA_la_dash#3]
SNA tab visualizes users connections between each other during the whole course. Stronger connections marks more than one activity (comment) between two users.

Click on a user's name opens popup with user's last 5 activities during the course and link to user's activity stream under user profile page.

![screen shot 2015-08-11 at 13 04 18](https://cloud.githubusercontent.com/assets/380007/9195176/7da9bf1e-4029-11e5-8252-a5400604123f.png)

**Comment by pjotrsavitski** [comment]
It is hard to know where the ActivityStream for the user resides (or the user profile). The information is probably not available within the LearningLocker stores and it is unclear how and where to get that information.

**Comment by pjotrsavitski** [comment]
Please consider which library would be the best to use.

One possible option could be this one: http://sigmajs.org
Looks simple and fast enough, although it does not have supreme looks.

We should probably start small and then see if it could/needs to be made batter.

**Comment by pjotrsavitski** [comment]
Another possibility is this one: https://github.com/anvaka/VivaGraphJS

**Comment by pjotrsavitski** [comment]
Done, create new smaller issues if changes are required.
