### ISSUE TITLE
Help-texts for Overview tab

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/EMMA_la_dash#32]
![screen shot 2016-06-08 at 10 46 54](https://cloud.githubusercontent.com/assets/380007/15886635/ce13d91e-2d66-11e6-8207-5e20859e1a83.png)

**Comment by tammets** [comment]
**Text A:**
Graphic combines list of all lessons, number of interactions and average time spent on lessons by users.

Interactions are page views which includes lessons, units, studu materials, assignments etc.

Time spent is a sum of time that user has spent on each page inside of the lesson.

**Text B:**
Most popular resources is a list of resources (pages, learning materials, blog posts etc). Number of views illustratates the number of clicks made on specific resource.

Note that some resources links to the same page but the title is in different language which visualises user preferences taking a specific course.

**Comment by pjotrsavitski** [comment]
This should have closed the issue: https://github.com/centre-for-educational-technology/EMMA_la_dash/commit/77205ce173a1d40ab8305eae5783268b278dadc2
