### ISSUE TITLE
Lessons

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/EMMA_la_dash#4]
Lessons tab visualizes activities related to specific lesson and unit. For each unit 3 different graphs and tables are presented:
1. Learning content

Learning content graph displays % on enrolled users who have accessed unit, accessed study materials and accessed hyperlinks within the unit. Hovering over graph bar, a popup appears which displays total amount of enrolled users who have accessed selected (hovered) data (for example: 45 enrolled users (22%) have accessed hyperlinks in current unit).
1. Assignments

Assignments graph visualizes % of enrolled users who have viewed and submitted assignments in current unit. Hovering over Viewed bar displays total amount of enrolled users who have viewed assignments in current unit and Submitted assignments bar displays total amount of submitted assignments and average score for all assignments within the unit.
1. Most popular resources

Table visualizes 10 most popular resources within selected unit. Resource name + language code, resource URL and total amount of views will be available for user.

![emma_analytics](https://cloud.githubusercontent.com/assets/380007/9195449/9d3fadb4-402b-11e5-9a6b-76b2f77d5809.png)

**Comment by pjotrsavitski** [comment]
I consider it almost done. Unless there are issues with queries, the data should be in.

**Comment by pjotrsavitski** [comment]
Done, create new smaller issues if changes are required.
