### ISSUE TITLE
Participants

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/EMMA_la_dash#5]
Participants tab gives an overview of total amount of users who have enrolled or left the course during the course.

Table beneath the graph displays all enrolled and unenrolled users as name+lastname+email+status

![screen shot 2015-08-11 at 13 22 21](https://cloud.githubusercontent.com/assets/380007/9195506/0355bd50-402c-11e5-8318-0459b694cfba.png)

**Comment by pjotrsavitski** [comment]
Status is not displayed and will not be.
